### ISSUE TITLE
key too large

### ISSUE THREAD

**Issue by jerzybrzoska** [dongyx/hardv#2]
When  I run `hardv fr.fc` I get the following error `fr.fc, line 3: key too large`. My file for learning, `fr.fc`, is,
```
%% This is a card set for hardv(1)
%% Created at Feb 1, 1997
Q    I know.
A    Je sais.
%%
Q    I love you.
A    Je't aime
%%
```

My environment: Ubuntu Desktop 22.04LTS, `hardv` compiled from source.

**Comment by dongyx** [comment]
The key and value should be separated by a tab character.
I suspect that the tab character is automatically replaced with white spaces by your editor.
Could you check that?

**Comment by jerzybrzoska** [comment]
Yes, one of my editors does this. Using `nano` and tabs solved this issue for me.
